Fix Convergence Test Setup
Now the convergence tests work as they should, in theory.

But test fails due to tolerance error.
Here are the last couple of lines of output:

Group: 4
	16.0	=>	0.13207818235126645	convergence: -
	32.0	=>	0.3957456477066952	convergence: 2.996298409484438
	64.0	=>	0.9211349098547714	convergence: 2.327593279149505
	128.0	=>	1.9642097120095618	convergence: 2.1323800574654634
	256.0	=>	4.020168234332415	convergence: 2.0467102925682124
	512.0	=>	8.016183859945558	convergence: 1.9939921398032532

Testing convergence
 + test_type: convergence
 + error_tolerance_convergence: 0.05
 + range start/end: 0, 4
	16.0	=>	0.13207818235126645	convergence: -	error: -
	32.0	=>	0.3957456477066952	convergence: 2.996298409484438	error: 0.4981492047422189
Error: 0.4981492047422189